<a href="https://colab.research.google.com/github/Adnan4555/ADNAN-4555/blob/DATA-SCIENCE/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np


In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8),(0,9,5,7)])

In [ ]:
print(b)

[[1 2 3 4]
 [5 6 7 8]
 [0 9 5 7]]


In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
a.shape

(3,)

In [ ]:
b.shape

(3, 4)

In [ ]:
c = np.array([(3,6,4,8),(4,5,0,7),(3,4,2,7)])

In [ ]:
c

array([[3, 6, 4, 8],
       [4, 5, 0, 7],
       [3, 4, 2, 7]])

In [ ]:
d = c.reshape(2,6)

In [ ]:
d

array([[3, 6, 4, 8, 4, 5],
       [0, 7, 3, 4, 2, 7]])

In [ ]:
e = np.array([1,4,7,8])

In [ ]:
print(e[2])

7


In [ ]:
f = np.array([(3,6,4,8),(4,5,0,7),(3,4,2,7)])

In [ ]:
print(f[2,3])

7


In [ ]:
val = np.array([[3,6,4,8],[4,5,0,7],[3,4,2,7]])

In [ ]:
print(val)

[[3 6 4 8]
 [4 5 0 7]
 [3 4 2 7]]


In [ ]:
val2 = val[:2,:2]

In [ ]:
print(val2)

[[3 6]
 [4 5]]


In [ ]:
val3 = val[:2,:3]

In [ ]:
val3

array([[3, 6, 4],
       [4, 5, 0]])

In [ ]:
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
arr2.ndim

3

In [ ]:
arr2.size

27

# 1d - 2d

In [ ]:
arr1 = np.array([1,2,3])

In [ ]:
arr1

array([1, 2, 3])

In [ ]:
arr1.size


3

In [ ]:
f = arr1.reshape(3,1)

In [ ]:
f

array([[1],
       [2],
       [3]])

#1d-3d

In [ ]:
newarr = arr1.reshape(1,1,3)

In [ ]:
newarr

array([[[1, 2, 3]]])

In [ ]:
newarr.ndim

3

#2d-2d

In [ ]:
newarr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
h = newarr1.reshape(3,3)

In [ ]:
h

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
h.ndim

2

#2d - 3d

In [ ]:
newarr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr3 = newarr1.reshape(1,3,3)

In [ ]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
arr3.ndim

3

# 3d - 2d

In [ ]:
arr5 = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])

In [ ]:
z = arr5.reshape(3,3)

In [ ]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
z.ndim

2

#datatype

In [ ]:
arr5.dtype

dtype('int64')

In [ ]:
arr7 = np.array([1.1,2.2,3.3])

In [ ]:
arr7

array([1.1, 2.2, 3.3])

In [ ]:
arr7.dtype

dtype('float64')

In [ ]:
strings = np.array(['a','b','c'])
strings

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
strings.dtype

dtype('<U1')

# converting to int

In [ ]:
arr9 = np.array([1, 2, 3, 4, 5],dtype=np.int64)

In [ ]:
arr9.dtype

dtype('int64')

#converting to float

In [ ]:
arr10 = np.array([1, 2, 3, 4, 5],dtype=np.float64)

In [ ]:
arr10.dtype

dtype('float64')